language: node_js

branches:
  only:
    - master

before_install:
  - npm i -g npm@6.14.4

cache:
  directories:
    - 'node_modules'

script:
  - npm run test
  - npm run lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
